### ISSUE TITLE
Not working in IE8! Please help.

### ISSUE THREAD

**Issue by emergingdzns** [firebase/firechat#39]
We have been using Firechat successfully built into our application for the past year. But recently it stopped working with Firebase discontinued the v1 of their js file. I upgraded to the latest firebase, which caused warnings which I was able to correct but ever since the update, the chat system won't load in IE8. I even checked the https://firechat.firebaseapp.com/ site on IE8 and sure enough it doesn't work there either.

This is absolutely critical because most of our users are in hospitals, most of which are on IE8.

Does anyone have any solution?

**Comment by katowulf** [comment]
Hi There! This isn't the right forum for authentication support, and you've also posted the [same issue to the mailing list](https://groups.google.com/forum/#!topic/firebase-talk/BEyvLCmnw1w). At the very least, those two posts should be linked so engineers aren't duplicating efforts.

For simplicity, let's just discuss on the list, since this isn't FireChat specific, but a question about the SDK.
