### ISSUE TITLE
Blank area

### ISSUE THREAD

**Issue by hallma** [firebase/firechat#50]

**Comment by katowulf** [comment]
It's going to be impossible to help you here, as none of us have access to your code, can see the results you're seeing, and you haven't included any error messages. 

Please include a [minimal repro](http://stackoverflow.com/help/mcve) showing how you arrive at these results (note that this isn't your entire web site; it's the relevant parts with everything else removed), including version info and steps to reproduce, and most importantly, the error messages in your console, networking tab, etc.

This serves several purposes:
 - it shows that you've performed due diligence and aren't trying to utilize your community as a debugger
 - it removes complexity and reduces the problems set so that we can understand it (keep in mind that we didn't write your app and can't understand all the components at a glance)
 - it provides us a way to verify the result and run the code
- it provides the error messages, which we may be familiar with

☼, Kato

**Comment by hallma** [comment]
I do not have very much experience with this so is it ok if I can give you the files on dropbox? https://www.dropbox.com/sh/f73n18njvxfzmbd/AAC7hoCMqatXesUfT-_24niha?dl=0 

Thank you very much for your help.

**Comment by katowulf** [comment]
Sure, dropbox files are just fine. But as previously mentioned, sending your entire website app is not. 

To make the point, the index.html file is 255 lines long. Is everything in there necessary to understand the problem? Is this somehow related to Google Analytics? No? Then remove that code. Unsure? Remove that code and see if the error goes away. Keep going until you have the minimal problem set.

Additionally, I specifically noted that you need to include version info, steps to reproduce, and the error messages encountered in your console. Please read about [creating a minimal, verifiable, reproducible example](http://stackoverflow.com/help/mcve), and pare this down to only the code related to your problem. The reason this is necessary is detailed in the bullet points above.

I know this creates some work on your part, but it's necessary for us to understand the problem within the time frame we have to devote to any single question.

☼, Kato

**Comment by hallma** [comment]
Ok I made it pretty minimal, and there were no errors in the log file...I commented on the area which I THINK is the problem but I can not be certain this is on line 77 - it may also be the authentication system but I think that is less likely.

**Comment by katowulf** [comment]
Here's the error I get in the javascript console:  

![image](https://cloud.githubusercontent.com/assets/959972/12869417/25c4f832-ccdc-11e5-88f2-e0bc8d8fbf2c.png)

**Comment by hallma** [comment]
ahh so that is in the config of my firebase? Do you know how I am meant to resolve this....this is what it looks like at the moment. https://gyazo.com/e3eeef4f56746f3acbc21efd00e4f39b

**Comment by hallma** [comment]
?
