### ISSUE TITLE
Update Firechat website to use the new Firebase logo

### ISSUE THREAD

**Issue by Stigelme** [firebase/firechat#67]
The Live Demo on firechat.firebaseapp.com should be updated: new Firebase Logo etc.

**Comment by jwngr** [comment]
The website, demo, and docs at [https://firechat.firebaseapp.com](https://firechat.firebaseapp.com) have been updated to the latest version of Firebase and to today's Firechat `3.0.0` release. Everything was updated except for the Firebase logos since I wasn't able to get new ones just yet. I'll keep this open (and rename the title) so that we know to update the logo at some point.

**Comment by jwngr** [comment]
This is fixed now and live!
